name: Build OpenRPI

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 18 * * *

    
env:
  SOURCE_URL: https://github.com/immortalwrt/immortalwrt
  SOURCE_BRANCH: openwrt-21.02
  INITIAL_BUILD_SCRIPT: curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash

jobs:
  Toolchain:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initial Build Enviroment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt upgrade -y
          $INITIAL_BUILD_SCRIPT
          sudo apt autoremove --purge
      
      - name: Git clone
        run: |
          git clone -b $SOURCE_BRANCH --single-branch $SOURCE_URL
          
      - name: Adding feeds
        run: |
          cd immortalwrt
          sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
          sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default
          git pull
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      
      - name: downloading packages
        run: |
          make defconfig
          make download -j8
      
      - name: making image
        run: |
          make -j$(nproc) V=s
      
          
